### ISSUE TITLE
Remove dependency on silverstripe/cms 

### ISSUE THREAD

**Issue by phptek** [phptek/silverstripe-verifiable#15]
Replace the dependency on silverstripe/cms in composer. The module should only need to depend on silverstripe/versioned.

**Comment by elliot-sawyer** [comment]
I don't think it even needs `versioned` as a dependency. You _can_ configure it to work with versioned DOs (and that is the stated use case) but it's not strictly required - the developer has to specifically configure the module to use it. Perhaps `"silverstripe/framework":"^4"` is all it needs?

**Comment by elliot-sawyer** [comment]
At any rate, this was raised after an attempt to install it on a vanilla recipe. Let's do something to make it work  :-D

**Comment by elliot-sawyer** [comment]
Ah, I see what you mean now - VerifiableExtension quite literally invokes `Versioned` so it must be a dependency! I'll update my PR to reflect that

**Comment by phptek** [comment]
Fixed in `a431053d29c9cefe3f14575438e9b76e0de74239`
