### ISSUE TITLE
Manual Data Verification

### ISSUE THREAD

**Issue by phptek** [phptek/silverstripe-verifiable#23]
## User Story

As a content author, I would like to manually verify that my data and its hash have been anchored to the backend properly, so that I be assured that my proof is always verifiable. 

## Acceptance Criteria

1). When I run a "Verify" process on a verified hash, in addition I can also see a full, v3 JSON-LD Chaincode Proof that;

 1.1. Highlights or the hash of my versioned data
 1.2. Highlights a link to ID of the backend's transaction (e.g. BTC's TXID) 
 1.3. Highlights a link to ID of the backend's block (e.g. BTC's Block ID) 

2). I can see the following information, that is not directly recoverable in the proof:

 2.1. I can manually regenerate a version's SHA256 hash, and compare it with its remote equivalent from the JSON-LD proof
 2.2. I can see the Merkle Root of which my SHA256 is a mathematical component
 2.3. I can manually calculate/verify that the Merkle Root Hash is in part composed of the current version's SHA256 hash, by means of the intermediate hashes available to me in the JSON-LD v3 chainpoint proof. 

## Technical Notes

For 2.1). This is mostly being done already and just needs to be lifted/adapted out of `VerifiableAdminController::getStatus()`

For 2.3). The most useful way I have seen so far, of calculating intermediate hashes, is to use a semi pre-baked method, as per the https://github.com/chainpoint/chainpoint-parse lib.

Useful resources:

* https://github.com/chainpoint/chainpoint-parse (JS)
* https://github.com/chainpoint/chainpoint-cli (JS)
* https://github.com/aantonop/chainpoint (Python)
* https://github.com/NebulousLabs/merkletree (Go)

**Comment by phptek** [comment]
This work is contingent on decoding the v3 chaincode proof out of REST API responses. These are comprised and base64 encoded strings that will need to be converted for display. See the github.com/chainpoint/chainpoint-cli JS project to see how this is done.

**Comment by phptek** [comment]
The JSON-LD formatted proof is actually available out of any node response that passes a "proof" field in its JSON data. It is a zlib, msgpack and base64 encoded string.

**Comment by phptek** [comment]
1. Using the [chainpoint-parse JS lib](https://github.com/chainpoint/chainpoint-parse), pass the parse() method the full JSON-LD v3 Chainpoint Proof
2. Observe the output contains:

	* The BTC TXID ("btcTxId" field) e.g. ba3c8c3e547ed73471c28a69659373f3f0a3b726aab31cdecd14513d9c581f1e (https://www.blockchain.com/btc/tx/ba3c8c3e547ed73471c28a69659373f3f0a3b726aab31cdecd14513d9c581f1e)
	* An OP_RETURN value e.g. 267335262e21e7adb4220068b4b90b7ff066324935d7f61ceab2a64080b06b1b
	* (AN OP_RETURN can be up to 80 bytes in length )
	* The "expected_value" field, is the Merkle Root value, anchored to the blockchain e.g. "c617f5faca34474bea7020d75c39cb8427a32145f9646586ecb9184002131ad9"
	* The "anchor_id" field's value is the block ID (In Bitcoin's case) e.g. "503275" (The Merkle Root is also found on blockchain.info when searhcing for this block ID)
	
What do we want to do?

1. Show the original SHA256 hash + intermediary Merkle Leaf Hashes taken from v3 Proof + link-to / show the TXID and Merkle Root on blockchain.info - as an HTML table?
2. Ditto, but display a visualisation of a Merkle Tree using the real data (Linked to blockchain.info where appropriate)
3. Something else?

**Comment by dcentrica** [comment]
Before this can be merged and considered complete - the following 3rd party package should be completed and then leveraged to display a visual representation of the hashing operations contained in any chainpoint recdeipt: https://github.com/dcentrica/chainpoint-receiptviz
